//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ContractID { get; set; }
        public Nullable<int> PeopleID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> PlanBegDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> Signed { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
    
        public virtual Peoples Peoples { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
