//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOSTELEntities : DbContext
    {
        public HOSTELEntities()
            : base("name=HOSTELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Buildings> Buildings { get; set; }
        public DbSet<Contracts> Contracts { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<Peoples> Peoples { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<Rooms> Rooms { get; set; }
        public DbSet<RoomTypes> RoomTypes { get; set; }
        public DbSet<Sexes> Sexes { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Workers> Workers { get; set; }
    }
}
