//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peoples
    {
        public Peoples()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Students = new HashSet<Students>();
            this.Workers = new HashSet<Workers>();
        }
    
        public int PeopleID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> SexID { get; set; }
        public string PspNum { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Images Images { get; set; }
        public virtual Sexes Sexes { get; set; }
        public virtual ICollection<Students> Students { get; set; }
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
