//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int RoomID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string Num { get; set; }
        public Nullable<int> PlacesCount { get; set; }
        public Nullable<int> RtyID { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual RoomTypes RoomTypes { get; set; }
    }
}
