//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sexes
    {
        public Sexes()
        {
            this.Peoples = new HashSet<Peoples>();
        }
    
        public int SexID { get; set; }
        public string Sex { get; set; }
    
        public virtual ICollection<Peoples> Peoples { get; set; }
    }
}
