//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_serv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentID { get; set; }
        public Nullable<int> PeopleID { get; set; }
        public Nullable<System.DateTime> Ad { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Peoples Peoples { get; set; }
    }
}
